name: Deploy Unskosfinder to VPS

on:
  push:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Executing remote ssh commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Memuat environment agar npm dan pm2 terbaca
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            
            # Tambahkan path npm/node secara manual jika tidak pakai NVM
            export PATH=$PATH:/usr/bin:/usr/local/bin

            cd /home/ubuntu/semar-kos-finder
            git pull origin main
            
            cd frontend
            npm install
            npm run build
            
            # Cek PM2 dengan path lengkap atau setelah source nvm
            pm2 describe semarkosfinder > /dev/null
            if [ $? -eq 0 ]; then
              pm2 restart semarkosfinder
            else
              pm2 start npm --name "semarkosfinder" -- start -- -p 3002
            fi
            pm2 save